"""SQL model definition file."""

from datetime import datetime
from typing import List
from zoneinfo import ZoneInfo

from sqlmodel import Field, Relationship, SQLModel


class Event(SQLModel, table=True):
    """Table that stores events

    Attributes:
        id(int, optional): Autogenerated id for the entity.
        title(str): Event title.
        start_date(datetime): Start date of the event in UTC.
        end_date(datetime): end date of the event in UTC.
        category(int): category id of the event.
        category_model(Category): Category of the event.
    """

    id: int | None = Field(default=None, primary_key=True)
    title: str = Field()
    start_date: datetime = Field(
        default_factory=lambda: datetime.now(ZoneInfo("UTC")), index=True
    )
    end_date: datetime = Field(
        default_factory=lambda: datetime.now(ZoneInfo("UTC")), index=True
    )
    category_id: int | None = Field(
        foreign_key="categories.id", index=True, default=None
    )
    category_model: "Category" = Relationship(back_populates="events")
    __tablename__ = "events"  # type: ignore


class Category(SQLModel, table=True):
    """Table that stores event categories (e.g.: work, personal, groceries, etc)

    Attributes:
        id(int, optional): Autogenerated id for the entity
        name(str): Category unique name
        transactions(list): list of events associated with a category
            (this is to allow accessing to events from a category on reverse)
    """

    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    events: List["Event"] = Relationship(back_populates="category_model")
    __tablename__ = "categories"  # type: ignore
